### ISSUE TITLE
In-Game: [macOS] Crash when Esc is pressed to end game when imGUI elements are present

### ISSUE THREAD

**Issue by cameron-home** [YoYoGames/GMEXT-AppleSignIn#1] opened 2024-02-22 12:17 UTC
### Description

When pressing the Esc key to close a macOS game that has imGUI elements present, e.g. on a main menu, the game will crash. This is similar behaviour to what occurs in YoYoGames/GameMaker#3638, with a similar crash log returned.

[crash log GUI elements.txt](https://github.com/YoYoGames/GameMaker/files/14373696/crash.log.GUI.elements.txt)
[YYGTest Crash.zip](https://drive.google.com/file/d/14UwUGjn0U0nLY8T8BTi2hHcue8nsNpmi/view?usp=sharing)

### Expected Change

It is expected that the game does not crash when Esc is pressed

### Steps To Reproduce

1. Start GameMaker
2. Open attached project
3. Run game
4. Press Esc key while on main menu
5. See the issue
Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.200.0.499  Runtime v2024.200.0.516

### Which platform(s) are you seeing the problem on?

Windows

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by rwkay** [comment] 2024-02-23 14:04
Looks like this is to do with the Extension Finalize process for the AppleSignInMac extension

OK the problem is that the Mac_AppleSignIn_Final extension function is marked as having a `string` return type

<img width="958" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/8b4eab03-bac0-437d-8116-7c94d9e8188c">

and the actual C++ return type is a double see https://github.com/YoYoGames/GMEXT-AppleSignIn/blob/31f3b474f1e9fb768e07cbff108eeb10bda0a58c/source/AppleSignIn_xcode/AppleSignInMacLib/AppleSignInMacLib.mm#L40

<img width="356" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/3646448/9b00d9d2-b741-47a0-bb6b-5ce2bd2b1574">

**Comment by DiasFranciscoA** [comment] 2024-03-04 13:16
This is now fixed in the new version of the extension **1.2.0**

**Closed as completed by DiasFranciscoA** 2024-03-04 13:16 UTC
Labels: AppleSignIn, project, extension
